name: Android CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Android Studio Arctic Fox and later uses Java 11+, current stable supports 17

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew # Ensure gradlew is executable

      - name: Build debug APK
        run: ./gradlew assembleDebug # Command to build the debug APK

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest # Command to run unit tests